version: '3.9'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_DB: traders_db
      POSTGRES_USER: trader_user
      POSTGRES_PASSWORD: trader_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  web:
    build: .
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             gunicorn traders_portal.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: traders_db
      POSTGRES_USER: trader_user
      POSTGRES_PASSWORD: trader_pass
      DB_HOST: db
      DB_PORT: 5432

volumes:
  postgres_data:
