# Generated by Django 4.2.23 on 2025-08-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='scripcode',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='symbol',
            field=models.CharField(max_length=50),
        ),
    ]
